friends=["Sumukh","Tejas","Shubham","Nikhil","Akut"]
numbers=[1,2,87,4,5,7]
friends.append("Arina")
friends.insert(1,"Dhanno")
friends.remove("Shubham")
numbers.pop()
#friends.clear()
#friends.extend(numbers)
print(friends)
print(friends.index("Arina"))
friends.pop()
print(friends)
print(numbers)
print(friends.count("Sumukh"))
numbers.sort()
#numbers.reverse
print(numbers)
friends2=friends.copy()
print(friends2)