print("Hrishikesh Karande")
print("Hrishikesh\nKarande")
print("\"Hrishikesh\" Karande")
name = "Hrishi"
print(name + " Karande")
print(name)
print(name.lower())
print(name.upper().isupper())
print(len(name))
print(name[3])
print(name.replace("H","1"))
print(name.index("s"))